version: '3'
services:
  mongodb:
    image: mdb
    container_name: clifford-db
    build: ./db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=radiant_clifford
      - MONGO_INITDB_USER=test
      - MONGO_INITDB_PWD=test
    ports:
      - 27017:27017
    networks:
      - clifford
    volumes:
      - mongo:/data/db
    
  webservice:
    image: ws
    container_name: clifford-ws
    build: ./webservice
    environment:
      PORT: :8080
      SOCKET: /home/ubuntu/embedded/thermo.sock
      KEY: thermo
      DB_URI: mongodb:27017
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8080:8080"
    networks:
      - clifford
    volumes:
      - /home/ubuntu/embedded/thermo.sock:/home/ubuntu/embedded/thermo.sock

networks:
  clifford:
    driver: "bridge"
volumes:
  mongo:
  thermo: