version: '3'
services:
  # Mock socket
  mock:
    image: mocker
    container_name: mock-srvc
    build: ./sock_mock
    restart: always
    environment:
      - KEY
    ports:
      - "9090:9090"
    networks:
      - clifford

  webservice:
    image: ws
    container_name: clifford-ws
    build: ./webservice
    env_file:
      - .env
    depends_on:
      - radiant_db
      - mock
    restart: always
    ports:
      - "8080:8080"
    expose: [8080]
    networks:
      - clifford

  radiant_db:
    image: "mongo:4.0"
    container_name: radiant-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_NAME
      - MONGO_USER
      - MONGO_PASS
      - MONGO_AUTH
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.js:ro
      - data:/data/db
    networks:
      - clifford

networks:
  clifford:
    driver: "bridge"

volumes:
  data:
