version: '3'
services:
  # Mock socket
  # mock:
  #   image: mocker
  #   container_name: mock-srvc
  #   build: ./sock_mock
  #   restart: always
  #   environment:
  #     KEY: "probe"
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - clifford
  webservice:
    image: ws
    container_name: clifford-ws
    build: ./webservice
    environment:
      PORT: ":8080"
      SENSOR_PORT: "192.168.1.90:8080"
      DB_HOST: "radiant_db"
      DB_PORT: "27017"
      DB_NAME: "radiant"
      DB_USER: "clifford"
      DB_PWD: "1234567"
      AUTH: "SCRAM-SHA-256"
      KEY: "probe"
    depends_on:
      - radiant_db
    restart: always
    ports:
      - "8080:8080"
    expose: [8080]
    networks:
      - clifford
  radiant_db:
    image: "mongo:4.0"
    container_name: radiant-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_NAME: "radiant"
      MONGO_USER: "clifford"
      MONGO_PASS: "1234567"
      MONGO_AUTH: "SCRAM-SHA-256"
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - data:/data/db
    networks:
      - clifford
networks:
  clifford:
    driver: "bridge"

volumes:
  data: