version: '3'
services:
  webservice:
    image: ws
    container_name: clifford-ws
    build: ./webservice
    environment:
      - PORT
      - SENSOR_PORT
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PWD
      - AUTH
      - KEY
    depends_on:
      - radiant_db
    restart: always
    ports:
      - "8080:8080"
    expose: [8080]
    networks:
      - clifford
  radiant_db:
    image: "mongo:4.0"
    container_name: radiant-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_NAME
      - MONGO_USER
      - MONGO_PASS
      - MONGO_AUTH
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - data:/data/db
    networks:
      - clifford
networks:
  clifford:
    driver: "bridge"

volumes:
  data: